name: Crystal CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        crystal_version:
          - 1.16.3
          - latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal_version }}
    
    - name: Cache shards
      uses: actions/cache@v3
      with:
        path: ~/.cache/shards
        key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
        restore-keys: |
          ${{ runner.os }}-shards-
    
    - name: Install dependencies
      run: shards install
    
    - name: Run tests
      run: crystal spec
    
    - name: Check formatting
      run: crystal tool format --check
    
    - name: Build
      run: shards build